permalink:   pretty
markdown:    rdiscount
rdiscount:
  extensions: [smart]
title: How nice!
description: mumumumumur
url: http://muan.co
auto: true
disqus_shortname: muan
feedburner_id: muan
facebook_appid: 604714799556697
facebook_userid: 1036039927