title:            Mu-An Chiou
description:      Mu-An Chiou's home page on the World Wide Web.
url:              https://muan.co
permalink:        /posts/:title
timezone:         Asia/Taipei
kramdown:
  hard_wrap: true
sass:
  sass_dir: assets
  style: :compressed
collections:
  notes:
    output: false
  pages:
    output: true
i18n:
  Travel: 旅
  Animals: 寵
  Taiwan: 台
  Books: 書
  Cook: 廚
  Plants: 植
  24h: 日
  Mails: 郵
  Friends: 友