title:            Mu-An Chiou
description:      Mu-An Chiou's home page on the World Wide Web.
url:              https://muan.co
permalink:        /posts/:title
timezone:         Asia/Taipei
kramdown:
  hard_wrap: true
sass:
  sass_dir: assets
  style: :compressed
collections:
  notes:
    output: false
  pages:
    output: true
